// getting necessary elements from the DOM

const studentList = document.querySelector('.student-list');
const studentItems = document.querySelectorAll('.student-item');
const pagination = document.querySelector('.pagination');
const pages = Math.ceil(studentItems.length / 10);
const searchButton = document.querySelector('.search');

//To throw an error if no student is found on search.
const h2 = document.createElement('h2');
h2.textContent = 'User Not Found';
h2.style.textAlign = 'center';
h2.style.display = 'none'; //initially declared the display to 'none'. To be set to '' where necessary.
const page = document.querySelector('.page');
page.insertBefore(h2, pagination);

//Adds pagination links on the bottom of the page
function addPagination(pages) {
    const ul = document.createElement('ul');
    pagination.appendChild(ul);
    for (let i = 1; i <= pages; i++) {
        const li = document.createElement('li');
        li.innerHTML = `<a href='#'> ${i} </a>`;
        ul.appendChild(li);
    }
}
addPagination(pages);

const paginationLinks = pagination.firstElementChild.childNodes;

//sets the class name of the pagination links to empty when called each time on clicking the link
// NOTE: className = 'active' sets certain styles on the active link element.
function setEmptyClassName() {
 for (let i = 0; i < paginationLinks.length; i++) {
        paginationLinks[i].firstElementChild.className = '';
    }
}

// Search and show the student record
searchButton.addEventListener('click', (e) => {
    const input = searchButton.previousElementSibling.value.toUpperCase();
    let userFound = false;
    for (let i = 0; i < studentItems.length; i++) {
        const name = studentItems[i].firstElementChild.firstElementChild.nextElementSibling.textContent.toUpperCase();
        if (name.includes(input)) {
            studentItems[i].style.display = '';
            userFound = true;
        } else {

            studentItems[i].style.display = 'none';
        }
    }
    searchButton.previousElementSibling.value = '';

    // if user not found prints user not found.
    if (userFound != true) {
        h2.style.display = '';
        setEmptyClassName();


    }

});


// Lists the 10 students per page based on which page is clicked
function listStudents(studentItems, index) {

    // loops through the studentItems from the provided 'index' value.
    for (let i = index; i < studentItems.length; i++) {
        //displays the 10 elements according to page number.
        if (i < index + 10) {
            studentItems[i].style.display = '';
        }
    }

    // change the display property to 'none' of the remaining students li.
    let counterr = index + 10;
    while (counterr < studentItems.length) {
        studentItems[counterr].style.display = 'none';
        counterr++;
    }
    for (let j = index - 1; j >= 0; j--) {
        studentItems[j].style.display = 'none';
    }

}

// Defines which students show up when according to the listStudents function

pagination.addEventListener('click', (e) => {

    setEmptyClassName();

    //sets the active link's className
    e.target.className = 'active';

    const page = parseInt(e.target.textContent);
    let counter = 0;
    for (let i = 1; i <= pages; i++) {

        if (page == i) {
            listStudents(studentItems, counter);
        }
        counter += 10;
    }
    // to remove the 'User Not Found' message generated by search student record
    h2.style.display = 'none';
});



listStudents(studentItems, 0);
